### ISSUE TITLE
Having deadnix as a transitive input breaks your flake

### ISSUE THREAD

**Issue by ursi** [astro/deadnix#17]
Introduced in: dd04c4bf35944590cb3e13e0aad6b79983103ccc

```
error: input 'nix-html/deadnix/fenix/nixpkgs' follows a non-existent input 'deadnix/nixpkgs'
```

It is a bug in nix that has been fixed in master, but there's no telling how long it'll be before that makes it into nix stable. Removing the `follows` fixes the issue.

**Comment by astro** [comment]
Thanks for the report.

Would it help to alternatively add nixpkgs as an explicit input? If so, which branch?

**Comment by ursi** [comment]
I definitely think it would be a good idea to add nixpkgs as an explicit input, but I just tested it and it does not fix the problem. Regarding what branch, `nixpkgs-unstable` should be fine.

**Comment by astro** [comment]
Done
