### ISSUE TITLE
unused args are not detected

### ISSUE THREAD

**Issue by Artturin** [astro/deadnix#24]
examples from https://github.com/NixOS/nixpkgs/pull/166605
`./pkgs/applications/blockchains/bisq-desktop/default.nix`
`./pkgs/applications/audio/caudec/default.nix`

gnutar was removed from bisq and bash from caudec

```
$ deadnix ./pkgs/applications/blockchains/bisq-desktop/default.nix
<no output>
$ deadnix ./pkgs/applications/audio/caudec/default.nix
<no output>
```

**Comment by astro** [comment]
The corresponding attrset lambda patterns don't have an ellipsis (`{ ... }:`). Deleting those identifiers changes code semantically, for example when used with eg. `callPackage`. That's just an explanation why I chose to ignore them if the ellipsis is missing. This might need some more thought...

**Comment by astro** [comment]
@supersandro2000 proposes that we should ignore attrset destructuring in absence of `...` when there is an `{ }@args` alias

**Comment by astro** [comment]
@Artturin Do you have an opinion ignoring only when there's an `@alias` to the lambda arg? That would replace the current check for `...`.

So far deadnix does what's intuitive for the language. I agree that we need acknowledge the `callPackage` practise in nixpkgs as it is very common.

**Comment by astro** [comment]
@Artturin I have changed the behaviour to check all lambda attrset args. Could you please evaluate deadnix' `main` branch, checking that it won't generate too many false positives?

**Comment by SuperSandro2000** [comment]
I used it a couple of times in the last days and so far did not encounter any bugs. Maybe some more complex situations could be buggy but we can only test that if more people would use it.

**Comment by Artturin** [comment]
i've been using it in my editor with https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#deadnix for ~3 days now and it has worked well
