### ISSUE TITLE
Merge with statix

### ISSUE THREAD

**Issue by hab25** [astro/deadnix#36]
This will likely help increase the discoverability and lower the barrier to entry of using both tools.

see also https://github.com/nerdypepper/statix/issues/41

**Comment by astro** [comment]
No serious objection but I would like to point out that the tools perform two very different things:
- statix looks for patterns in a very narrow scope
- deadnix performs deep scope usage analysis for every identifier

**Comment by hab25** [comment]
I don't understand that difference well enough, but it seems to me like something that is primarily relevant for maintainers but not so much to an end-user.

**Comment by astro** [comment]
Even end-users care about the *UNIX Philosophy™*:

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".

**Comment by hab25** [comment]
Good point. I also approve of the UNIX philosophy, and in accordance with it I think a new metalinter project is better than merging. I say "new" only because I don't know of any existing ones.

Feel free to close this issue if you want.

**Comment by astro** [comment]
BTW, does nix-community have a Hydra that can build aarch64 along with kvm enabled? Care to add my microvm.nix flake?
