### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hab25** [astro/deadnix#37]
When I checked, there were no open issues. However, deadnix is at version 0.x, if we assume semantic versioning we can infer that development has not finished. 

Many like to wait for 1.0 before deciding to use a tool due to not wanting to deal with frequent breaking changes. Seeing a roadmap will help them predict when they'll be able to use it, as well as what kind of tool it will be by that point (using a github issue tag such as "enhancement" also helps with the latter).

This can be very simple, e.g. https://github.com/nerdypepper/statix#todo, but it would be better to have something like a Github milestone.

**Comment by astro** [comment]
Published v1.0.0
