### ISSUE TITLE
feature request: exclude parameter

### ISSUE THREAD

**Issue by phip1611** [astro/deadnix#53]
It would be convenient to have the following parameter: `--exclude foobar.nix --exclude foo/**/*bar.nix` and possibly also a `--enable|disable-default-excludes`. For example, `source.nix` by `nix` is a good candidate for a default exclusion.

**Comment by astro** [comment]
Basic functionality is here!

A PR adding glob pattern support would be welcome.

I don't like hardcoding default paths, and I can't think of any sensible source from which to obtain them.
