### ISSUE TITLE
Exclude pattern syntax is too strict

### ISSUE THREAD

**Issue by samhh** [astro/deadnix#64]
Given a potential lint in `./foo/bar.nix`, I see the following behaviour in my shell:

```console
$ deadnix --exclude ./foo/**/* # works as expected
$ deadnix --exclude foo/**/* # does not work
$ deadnix --exclude './foo/**/*' # does not work
```

The last one I understand if you want to offload to the shell, however I'd have expected the second one to work. As much as I like to be explicit about `./`, most tools don't require it.

I don't think my shell is behaving abnormally as if I pass the globs to `echo` they expand identically bar the prefixed `./` (real example):

```console 
$ echo ./templates/**/*
./templates/default.nix ./templates/devshell-flake-parts ./templates/devshell-flake-parts/flake.nix ./templates/devshell-flake-utils ./templates/devshell-flake-utils/flake.nix
$ echo templates/**/*
templates/default.nix templates/devshell-flake-parts templates/devshell-flake-parts/flake.nix templates/devshell-flake-utils templates/devshell-flake-utils/flake.nix
```

**Comment by astro** [comment]
#65 just introduced canonicalization of paths which improves this a lot.
