### ISSUE TITLE
Don't mark required attributes in an attribute set as unused

### ISSUE THREAD

**Issue by phip1611** [astro/deadnix#67]
Hi,

Suppose the following code snippet (with focus on `makeGenericEnvironment`):

```nix
let
  kernel = ...;
  makeGenericEnvironment =
    { testNamePrefix
    , isNative
    , ...
    }@environment: {
      inherit foobar;
    } // environment;
in
{
  one = makeGenericEnvironment {
    testNamePrefix = "TestFOO";
    isNative = true;
    foo = "bar";
  };
  two = makeGenericEnvironment {
    testNamePrefix = "TestBAR";
    isNative = false;
    bar = "foo";
  };
}
```

The idea is to force users to always provide `testNamePrefix` and `isNative`. Apart from that, arbitrary attributes can be passed. Inside `makeGenericEnvironment`, the provided attribute set is merged with some predefined attributes (here, `foobar`).

However, `deadnix` tells that `testNamePrefix` and `isNative` are unused. Well, regarding the AST, they are technically. To satisfy deadnix, I have to add `inherit testNamePrefix isNative;`.

Is there a solution how deadnix can find out that this is valid?

**Comment by astro** [comment]
Run deadnix with `-L`, `--no-lambda-pattern-names`

Would that work for you?

Side note: because that flag is already needed when deadnixing nixpkgs, it would have been smarter to make it default behavior, with opt-in to checking. Too late now. I don't like breaking changes.

**Comment by phip1611** [comment]
yes, thanks. That helps
