### ISSUE TITLE
Joining nix-community

### ISSUE THREAD

**Issue by IogaMaster** [astro/deadnix#71]
Hey @astro, great project!

Would you like to add it to the wider nix-community organization?
https://github.com/nix-community/

**Comment by astro** [comment]
Why?

**Comment by IogaMaster** [comment]
1. Ecosystem Synergy: A lot of similar projects are in the nix-community organization, these include nixd, rnix-lsp, nixpkgs-hammering, nurl, and most recently manix. I think that this project would fit nicely amongst those.

2.  nix-community provides infrastructure and support for those projects as well as increased visibility.

**Comment by astro** [comment]
Following #36, deadnix can already be used as a Rust crate in other projects.

With nil (not under nix-commnuity either) now performing the same analysis, this project may become obsolete one day.

Moving this repo under another account would make me less visible. :-)

**Comment by IogaMaster** [comment]
> With nil (not under nix-commnuity either)

Some members are going to approach oxacila to move nil-ls into nix-community.

> Moving this repo under another account would make me less visible. :-)

Normally we have something like this for a description of a project.

```
Scan Nix files for dead code [maintainer=@astro] 
```
I do understand that you would like to keep 100% ownership of the repo.

> this project may become obsolete one day.

If that is the case leaving deadnix under the same historical ownership would be beneficial.

Thank you for taking the time to respond! Have a great day!

**Comment by astro** [comment]
BTW, does nix-community have a Hydra that can build aarch64 along with kvm enabled? Could someone add my microvm.nix flake?

**Comment by IogaMaster** [comment]
> BTW, does nix-community have a Hydra that can build aarch64 along with kvm enabled?

Idk, I am looking rn.

> Could someone add my microvm.nix flake?
Do you mean add that project to nix-community to gain those benifits

**Comment by IogaMaster** [comment]
There are aarch64 builders, i do not know about kvm support.
