### ISSUE TITLE
Usage: false-positive (recent regression)

### ISSUE THREAD

**Issue by Kernald** [astro/deadnix#91]
Following e3b63f46edb2917f2b7d0c6833db7ebfc5d29c92, deadnix is suggesting to remove a bunch of `config` from module arguments, despite being used (at least, but maybe not only, in interpolated strings, e.g. `foo${config.bar}`). 152c31698275d4be92347ff475217e32a66f4caa works just fine.

**Comment by astro** [comment]
Please help me reproduce. This for example has no unused bindings:

```nix
{ config, ... }:

"${config.bar}"
```

**Comment by astro** [comment]
After another day of thinking, I guess you mean something like this:

```nix
{ config, ... }: {

  "${config.bar}" = 42;
}
```

**Comment by astro** [comment]
Thank you for reporting!

**Comment by Kernald** [comment]
Sorry for the delay - this is indeed the case I had. Fixed at `HEAD`, thanks!
